Administratoren:
  access:
    site:
      login: true
    admin:
      login: true
      super: true
      cache: true
      configuration: true
      pages: true
      maintenance: true
      statistics: true
      plugins: true
      themes: true
      tools: true
      users: true
      flex-objects: true
  readableName: Administratoren
  enabled: true
Chormitglieder:
  access:
    site:
      login: true
    admin:
      pages:
        create: false
        read: true
        update: false
        delete: false
        list: true
  readableName: Chormitglieder
  enabled: true
Choerchenadmin:
  access:
    site:
      login: true
    admin:
      login: true
      super: false
      cache: false
      configuration: false
      pages:
        create: false
        read: true
        update: true
        delete: false
        list: true
      maintenance: false
      statistics: false
      plugins: false
      themes: false
      tools: false
      users: false
      flex-objects: false
  readableName: Chörchenadmin
  enabled: true
